export const caseDossierIds = Object.freeze({
  account: '10000000-0000-4000-8000-000000000001',
  ownerCase: '20000000-0000-4000-8000-000000000002',
  foreignCase: '30000000-0000-4000-8000-000000000003',
  subject: '40000000-0000-4000-8000-000000000004',
  evidence: '50000000-0000-4000-8000-000000000005',
});

export const caseDossierSnapshot = Object.freeze({
  contractVersion: 'case-dossier-v1',
  generatedAtUtc: '2026-07-16T09:30:00Z',
  audience: {
    scope: 'current-account',
    accountReference: caseDossierIds.account.replaceAll('-', ''),
  },
  state: 'found',
  case: {
    caseId: caseDossierIds.ownerCase.replaceAll('-', ''),
    caseNumber: 'А40-1234/2026',
    courtDiscriminator: '40',
  },
  subjects: [{
    subjectReference: caseDossierIds.subject.replaceAll('-', ''),
    subjectType: 'organization',
    inn: '7707083893',
    ogrn: '1027700132195',
    displayName: 'Тестовая организация',
    identityConfidence: 'exact-inn',
    identityProvenance: 'source-validated',
  }],
  subjectsTotal: 1,
  subjectsReturned: 1,
  subjectsTruncated: false,
  bankruptcy: {
    collectionState: 'collected',
    presentationState: 'found',
    projections: [{
      subjectReference: caseDossierIds.subject.replaceAll('-', ''),
      collectionState: 'collected',
      presentationState: 'found',
      authorityAtUtc: '2026-07-16T09:00:00Z',
      updatedAtUtc: '2026-07-16T09:10:00Z',
      authorityMembers: [{
        memberOrdinal: 1,
        actualSourceStatus: 'found',
        retryable: false,
        safeCode: 'bankruptcy-data-found',
        confidence: 'source-confirmed',
        sourceFetchedAtUtc: '2026-07-16T09:00:00Z',
        linkedAtUtc: '2026-07-16T09:05:00Z',
        canonicalCaseCount: 1,
        canonicalEvidenceCount: 3,
        evidence: [{
          evidenceReference: caseDossierIds.evidence.replaceAll('-', ''),
          source: 'fedresurs',
          messageType: 'Сообщение о банкротстве',
          publicationDateUtc: '2026-07-15T12:00:00Z',
          fetchedAtUtc: '2026-07-16T09:00:00Z',
          confidence: 'source-confirmed',
          sourceReference: 'https://fedresurs.ru/bankruptmessages/fixture-message',
          normalizedCaseNumber: 'А40-1234/2026',
        }],
        caseEvidenceTotal: 1,
        caseEvidenceReturned: 1,
        caseEvidenceTruncated: false,
        otherCaseEvidenceCount: 2,
      }],
      authorityMembersTotal: 1,
      authorityMembersReturned: 1,
      authorityMembersTruncated: false,
      priorAuthority: null,
    }],
    projectionsTotal: 1,
    projectionsReturned: 1,
    projectionsTruncated: false,
    authorityMembersTotal: 1,
    authorityMembersReturned: 1,
    authorityMembersTruncated: false,
    caseEvidenceTotal: 1,
    caseEvidenceReturned: 1,
    caseEvidenceTruncated: false,
  },
  timeline: {
    collectionState: 'collected',
    authorityState: 'single',
    actualStatus: 'found',
    presentationStatus: 'found',
    safeCode: 'case-data-found',
    retryable: false,
    freshness: 'as-observed',
    confidence: 'operator-asserted-unverified',
    authorityAtUtc: '2026-07-16T08:30:00Z',
    sourceUpdatedAtUtc: '2026-07-16T08:00:00Z',
    locallyUpdatedAtUtc: '2026-07-16T08:30:00Z',
    latestEvent: {
      occurredAtUtc: '2026-07-15T10:00:00Z',
      sourceUpdatedAtUtc: '2026-07-15T11:00:00Z',
      eventType: 'hearing',
      title: 'Судебное заседание',
      summary: 'Назначено судебное заседание.',
      revision: 1,
      documents: [{
        documentDate: '2026-07-15',
        documentType: 'ruling',
        name: 'Определение',
        summary: 'Определение о назначении заседания.',
        sourceReference: 'https://kad.arbitr.ru/Card/fixture-case',
      }],
      documentCount: 1,
      returnedDocumentCount: 1,
      documentsTruncated: false,
    },
    events: [{
      occurredAtUtc: '2026-07-15T10:00:00Z',
      sourceUpdatedAtUtc: '2026-07-15T11:00:00Z',
      eventType: 'hearing',
      title: 'Судебное заседание',
      summary: 'Назначено судебное заседание.',
      revision: 1,
      documents: [{
        documentDate: '2026-07-15',
        documentType: 'ruling',
        name: 'Определение',
        summary: 'Определение о назначении заседания.',
        sourceReference: 'https://kad.arbitr.ru/Card/fixture-case',
      }],
      documentCount: 1,
      returnedDocumentCount: 1,
      documentsTruncated: false,
    }],
    eventsTotal: 1,
    eventsReturned: 1,
    eventsTruncatedBefore: false,
    documentsTotal: 1,
    documentsReturned: 1,
    documentsTruncated: false,
  },
  watch: {
    directWatch: null,
    indirectWatchCount: 1,
  },
  sourceIssues: [],
  sourceIssuesTotal: 0,
  sourceIssuesReturned: 0,
  sourceIssuesTruncated: false,
  allowedActions: ['export-json', 'print', 'create-direct-watch'],
  caveats: [
    'decision-support-not-legal-advice', 'local-evidence-only',
    'source-freshness-must-be-reviewed', 'snapshot-generated-for-current-account',
    'operator-asserted-unverified',
  ],
});

export const caseDossierBytes = Buffer.from(
  JSON.stringify(caseDossierSnapshot),
  'utf8',
);

export const caseDossierProblems = Object.freeze({
  timeout: { code: 'case-dossier-timeout', title: 'Case dossier request timed out.', status: 408 },
  limited: { code: 'case-dossier-rate-limited', title: 'Case dossier request rate limit exceeded.', status: 429 },
  unavailable: { code: 'case-dossier-unavailable', title: 'Case dossier is temporarily unavailable.', status: 500 },
});
