export type StatusView = { label: string; description: string };
export type CreateInput = { inn?: string | null; ogrn?: string | null; name?: string | null; displayLabel?: string | null };
export function normalizeCounterpartyText(value: unknown, maxLength: number): string;
export function validateInn(value: unknown): string | null;
export function validateOgrn(value: unknown): string | null;
export function validateCounterpartyCreate(input: CreateInput): Record<string, string>;
export function identityStatusView(value: string): StatusView;
export function sourceStatusView(value: string, freshness: string): StatusView;
export function freshnessStatusView(value: string): StatusView;
export function emptyHistoryMessage(identity: string, source: string, freshness: string): string;
export type MonitoringTimeView = { accepted: true; label: string; dateTime: string } | { accepted: false; label: string; dateTime: null };
export function monitoringTimeView(value: string | null | undefined, referenceNow?: number, maxFutureSkewMs?: number): MonitoringTimeView;
export function formatMoscowDate(value?: string | null, referenceNow?: number): string;
export function safeFedresursEvidenceUrl(value: unknown): string | null;
export function mergeById<T extends { id: string }>(current: T[], incoming: T[], reset?: boolean): T[];
export function completeCounterpartyUpdate<T extends { enabled: boolean; alertOptIn: boolean; displayLabel: string | null; version: number }>(item: T, changes: Partial<Pick<T, 'enabled' | 'alertOptIn' | 'displayLabel'>>): { enabled: boolean; alertOptIn: boolean; displayLabel: string | null; version: number };
export function safeCounterpartyError(status: number): string;
export function dueDiligenceReportCopy(key: string): string;
export function dueDiligenceReportLevelLabel(level: string): string;
export function dueDiligenceReportFailureCopy(status: number): string;
export function dueDiligenceReasonView(reason: { code: string; source: string; evidenceCount: number }): { code: string; summary: string };
export function dueDiligenceSourceSummaryView(source: { source: string; state: string; freshness: string; confidence: string; evidenceCount: number }): { source: string; summary: string };
export type DueDiligenceReportClosedState = { status: 'closed' };
export type DueDiligenceReportLoadingState = { status: 'loading'; ownerKey: string; entryId: string; generation: number };
export type DueDiligenceReportReadyState<T = unknown> = { status: 'ready'; ownerKey: string; entryId: string; generation: number; rawText: string; report: T };
export function emptyDueDiligenceReport(): DueDiligenceReportClosedState;
export function beginDueDiligenceReport(ownerKey: string, entryId: string, generation: number): DueDiligenceReportLoadingState;
export function completeDueDiligenceReport<T, S>(state: S, ownerKey: string, entryId: string, generation: number, rawText: string, report: T): DueDiligenceReportReadyState<T> | S;
