import http from 'node:http';
const runId = '11111111-1111-4111-8111-111111111111'; const taskId = '22222222-2222-4222-8222-222222222222'; const taskId2='22222222-2222-4222-8222-222222222223'; const activeRunId='55555555-5555-4555-8555-555555555555'; const maxRunId='66666666-6666-4666-8666-666666666666';
const privacy = { 'cache-control': 'private, no-store, max-age=0', pragma: 'no-cache', vary: 'Authorization, Cookie', 'referrer-policy': 'no-referrer', 'x-content-type-options': 'nosniff' };
const cors = (origin) => ({ 'access-control-allow-origin': origin, 'access-control-allow-credentials': 'true', 'access-control-allow-methods': 'GET,POST,OPTIONS', 'access-control-allow-headers': 'content-type,idempotency-key', 'access-control-expose-headers': 'content-disposition,content-type,content-length,cache-control,pragma,vary' });
const json = (res, status, value, headers) => { const bytes = Buffer.from(JSON.stringify(value)); res.writeHead(status, { ...headers, 'content-type': 'application/json; charset=utf-8', 'content-length': bytes.length }); res.end(bytes); };
const empty = (res, status, headers) => { res.writeHead(status, { ...headers, 'content-length': 0 }); res.end(); };
const run = (authority='2026-07-17T10:01:00Z') => ({ id:runId,sourceFamily:'fedresurs',status:'failed',stopReason:'retry-budget-exhausted',totalTasks:1,pendingTasks:0,processingTasks:0,completedTasks:0,retryScheduledTasks:0,failedTasks:1,canceledTasks:0,createdAtUtc:'2026-07-17T10:00:00Z',updatedAtUtc:authority,startedAtUtc:'2026-07-17T10:00:10Z',finishedAtUtc:authority,cancelRequestedAtUtc:null,freshness:'terminal',resultFreshness:'unavailable',sourceControls:{policyVersion:'parser-run-source-controls/v1',environment:'development',adminOverride:false,maxConcurrency:1,requestDelayMs:5000,maxRetries:2,pageTimeoutSeconds:90,maxRows:100,captchaMode:'disabled',proxyMode:'disabled',proxyReference:null,proxyConfigured:false,diagnostics:['proxy-disabled','captcha-disabled','safe-defaults']},sourceStatusCounts:{'captcha-blocked':0,'rate-limited':0,'source-unavailable':1,timeout:0,'schema-changed':0},runAllowedActions:{cancel:false,resume:false,retryFailed:true,export:true},caveatCodes:['live-keyset-not-snapshot','redacted-operator-view']});
const activeRun=()=>({...run(),id:activeRunId,sourceFamily:'kad',status:'processing',stopReason:null,pendingTasks:0,processingTasks:1,failedTasks:0,updatedAtUtc:'2026-07-17T10:01:00Z',finishedAtUtc:null,freshness:'active-fresh',runAllowedActions:{cancel:true,resume:false,retryFailed:false,export:true},sourceStatusCounts:{'captcha-blocked':0,'rate-limited':0,'source-unavailable':0,timeout:0,'schema-changed':0}});
const task = () => ({ id:taskId,rowNumber:1,source:'fedresurs',targetType:'inn',inputDisplay:'77***67',status:'failed',stopReason:'retry-budget-exhausted',attemptCount:1,maxAttempts:3,nextAttemptAtUtc:null,resultKind:null,diagnosticCode:'source-unavailable',createdAtUtc:'2026-07-17T10:00:00Z',updatedAtUtc:'2026-07-17T10:01:00Z',startedAtUtc:'2026-07-17T10:00:10Z',finishedAtUtc:'2026-07-17T10:01:00Z',retryable:true,finding:'not-applicable',freshness:'terminal',resultFreshness:'unavailable',taskAllowedActions:{selectForRetry:true},caveatCodes:['redacted-operator-view']});
const task2=()=>({...task(),id:taskId2,rowNumber:2,inputDisplay:'78***68'});
const maxRun=()=>({...activeRun(),id:maxRunId,sourceFamily:'parser-load',status:'pending',stopReason:null,totalTasks:500,pendingTasks:500,processingTasks:0,runAllowedActions:{cancel:true,resume:false,retryFailed:false,export:true},freshness:'queued',startedAtUtc:null});
const statuses=['pending','processing','done-found','done-no-data','invalid','ambiguous','retry-scheduled','captcha-blocked','rate-limited','source-unavailable','timeout','schema-changed','failed','canceled'];
const stopFor=(status)=>({pending:null,processing:null,'done-found':'completed','done-no-data':'no-data',invalid:'invalid-input',ambiguous:'ambiguous-match','retry-scheduled':'retry-scheduled','captcha-blocked':'retry-scheduled','rate-limited':'retry-scheduled','source-unavailable':'retry-scheduled',timeout:'retry-scheduled','schema-changed':'schema-changed',failed:'retry-budget-exhausted',canceled:'canceled'})[status];
const guidFor=(prefix,index)=>`${prefix}0000000-0000-4000-8000-${String(index).padStart(12,'0')}`;
const maxTask=(index)=>{const status=statuses[(index-1)%statuses.length];const terminal=['done-found','done-no-data','invalid','ambiguous','schema-changed','failed','canceled'].includes(status);const retryable=['retry-scheduled','captcha-blocked','rate-limited','source-unavailable','timeout','failed'].includes(status);return {id:guidFor('7',index),rowNumber:index,source:'fedresurs',targetType:'inn',inputDisplay:`row-${index}`,status,stopReason:stopFor(status),attemptCount:status==='pending'?0:1,maxAttempts:3,nextAttemptAtUtc:status==='retry-scheduled'?'2026-07-17T10:01:30Z':null,resultKind:status==='done-found'?'found':null,diagnosticCode:null,createdAtUtc:'2026-07-17T10:00:00Z',updatedAtUtc:'2026-07-17T10:01:00Z',startedAtUtc:status==='pending'?null:'2026-07-17T10:00:10Z',finishedAtUtc:terminal?'2026-07-17T10:01:00Z':null,retryable,finding:status==='done-found'?'found':status==='done-no-data'?'no-data':'not-applicable',freshness:terminal?'terminal':status==='processing'?'active-fresh':'queued',resultFreshness:'unavailable',taskAllowedActions:{selectForRetry:status==='retry-scheduled'||status==='failed'},caveatCodes:['redacted-operator-view']};};
const maxAttempt=(index)=>({id:guidFor('8',index),attemptNumber:index,source:'fedresurs',status:'failed',stopReason:'retry-budget-exhausted',retryable:false,diagnosticCode:'source:http-timeout',startedAtUtc:'2026-07-17T10:00:10Z',finishedAtUtc:'2026-07-17T10:01:00Z',freshness:'terminal',caveatCodes:['redacted-operator-view']});
const familyOf=(url,method)=>url.pathname.endsWith('/export')?'export':url.pathname.endsWith('/attempts')?'attempt':url.pathname.endsWith('/tasks')?'task':method==='POST'?'action':'runs';
const holdIfRequested=async(req,mode,family,held)=>{if(mode!==`hold-${family}`)return 200;return new Promise((resolve)=>{held.push(resolve);req.once('aborted',()=>resolve(499));});};
export function createParserOperationsMock(origin) { let mode='ok';let holdHits=0;let held=[];let listHits=0;let taskHits=0;let attemptHits=0;let actionHits=0;let exportHits=0;let inFlightRuns=0;let maxInFlightRuns=0;let actionKeys=[]; return http.createServer(async (req,res)=>{ const url=new URL(req.url??'/','http://127.0.0.1'); const headers={...cors(origin),...privacy}; if(req.method==='OPTIONS')return empty(res,204,cors(origin)); if(url.pathname==='/__parser/control'){const command=url.searchParams.get('mode')??'ok';if(command==='state')return json(res,200,{mode,holdHits,held:held.length,listHits,taskHits,attemptHits,actionHits,exportHits,inFlightRuns,maxInFlightRuns,actionKeys},cors(origin));if(command==='release'){const status=Number(url.searchParams.get('status')??'200');for(const release of held)release(status);held=[];mode='ok';return json(res,200,{mode,holdHits,listHits,taskHits,attemptHits,actionHits,exportHits,inFlightRuns,maxInFlightRuns,actionKeys},cors(origin));}mode=command;return json(res,200,{mode,holdHits,listHits,taskHits,attemptHits,actionHits,exportHits,inFlightRuns,maxInFlightRuns,actionKeys},cors(origin));} const authorized=(req.headers.cookie??'').includes('parser-admin=1'); if(url.pathname==='/api/auth/me')return authorized?json(res,200,{id:mode==='auth-user2'?'admin-2':'admin-1',email:mode==='auth-user2'?'admin2@example.test':'admin@example.test',name:'Admin',isAdmin:true},cors(origin)):empty(res,401,cors(origin)); if(url.pathname==='/api/auth/logout')return empty(res,204,cors(origin)); if(!url.pathname.startsWith('/api/parser-operations/'))return empty(res,404,cors(origin)); const family=familyOf(url,req.method);if(!authorized||mode==='401'||mode===`401-${family}`)return empty(res,401,headers); if(mode==='403'||mode===`403-${family}`)return empty(res,403,headers);
    if(url.pathname==='/api/parser-operations/runs'){listHits+=1;inFlightRuns+=1;maxInFlightRuns=Math.max(maxInFlightRuns,inFlightRuns);try{if(mode==='hold-runs'){holdHits+=1;const status=await new Promise((resolve)=>{held.push(resolve);req.once('aborted',()=>resolve(499));});if(status!==200){if(!res.headersSent&&!res.writableEnded&&!res.destroyed)return empty(res,status===499?500:status,headers);return;}}const items=mode==='malformed-runs'?[{...run(),privatePayload:'never-render'}]:[run(),activeRun(),maxRun()];const firstPage=!url.searchParams.has('cursor');return json(res,200,{authorityAtUtc:'2026-07-17T10:02:00Z',items,nextCursor:firstPage?'r1':null,hasMore:firstPage},headers);}finally{inFlightRuns-=1;}}
    if(url.pathname===`/api/parser-operations/runs/${runId}/tasks`){taskHits+=1;const heldStatus=await holdIfRequested(req,mode,'task',held);if(heldStatus!==200)return !res.writableEnded&&!res.destroyed?empty(res,heldStatus===499?500:heldStatus,headers):undefined;return json(res,200,{authorityAtUtc:'2026-07-17T10:02:00Z',runId,items:[task(),task2()],nextCursor:null,hasMore:false},headers);}
    if(url.pathname===`/api/parser-operations/runs/${maxRunId}/tasks`){taskHits+=1;const start=Number((url.searchParams.get('cursor')??'t0').slice(1));const size=Math.min(200,500-start);return json(res,200,{authorityAtUtc:'2026-07-17T10:02:00Z',runId:maxRunId,items:Array.from({length:size},(_,offset)=>maxTask(start+offset+1)),nextCursor:start+size<500?`t${start+size}`:null,hasMore:start+size<500},headers);}
    if(url.pathname===`/api/parser-operations/runs/${runId}/tasks/${taskId}/attempts`){attemptHits+=1;const heldStatus=await holdIfRequested(req,mode,'attempt',held);if(heldStatus!==200)return !res.writableEnded&&!res.destroyed?empty(res,heldStatus===499?500:heldStatus,headers):undefined;return json(res,200,{authorityAtUtc:'2026-07-17T10:02:00Z',runId,taskId,items:[{id:'33333333-3333-4333-8333-333333333333',attemptNumber:1,source:'fedresurs',status:'source-unavailable',stopReason:'retry-scheduled',retryable:true,diagnosticCode:'source:http-timeout',startedAtUtc:'2026-07-17T10:00:10Z',finishedAtUtc:'2026-07-17T10:01:00Z',freshness:'terminal',caveatCodes:['redacted-operator-view']}],nextCursor:null,hasMore:false},headers);}
    if(url.pathname.startsWith(`/api/parser-operations/runs/${maxRunId}/tasks/`)&&url.pathname.endsWith('/attempts')){attemptHits+=1;const requestedTaskId=url.pathname.split('/').at(-2);const start=Number((url.searchParams.get('cursor')??'a0').slice(1));const size=Math.min(100,4096-start);return json(res,200,{authorityAtUtc:'2026-07-17T10:02:00Z',runId:maxRunId,taskId:requestedTaskId,items:Array.from({length:size},(_,offset)=>maxAttempt(start+offset+1)),nextCursor:start+size<4096?`a${start+size}`:null,hasMore:start+size<4096},headers);}
    if(url.pathname.endsWith('/export')){exportHits+=1;const heldStatus=await holdIfRequested(req,mode,'export',held);if(heldStatus!==200)return !res.writableEnded&&!res.destroyed?empty(res,heldStatus===499?500:heldStatus,headers):undefined;const bytes=Buffer.from('PK\u0003\u0004synthetic-redacted-zip,"\'=cmd|\'/C calc\'!A0"');const exportRunId=url.pathname.split('/').at(-2);const filename=`parser-run-${exportRunId}.zip`;res.writeHead(200,{...headers,'content-type':'application/zip','content-disposition':mode==='export-bad-disposition'?'attachment; filename="evil.zip"':`attachment; filename="${filename}"; filename*=UTF-8''${filename}`,'content-length':bytes.length});return res.end(bytes);}
    if(req.method==='POST'){actionHits+=1;actionKeys.push(req.headers['idempotency-key']??'');for await(const chunk of req){if(!chunk)break;}if(mode==='hold-action'){holdHits+=1;const status=await new Promise((resolve)=>{held.push(resolve);req.once('aborted',()=>resolve(499));});if(status!==200){if(!res.headersSent&&!res.writableEnded&&!res.destroyed)return empty(res,status===499?500:status,headers);return;}}if(mode==='action-drop'){req.socket.destroy();return;}if(mode==='action-400')return json(res,400,{code:'parser-operation-bad-request'},headers);if(mode==='action-404')return json(res,404,{code:'parser-operation-not-found'},headers);if(mode==='action-409')return json(res,409,{code:'parser-operation-conflict'},headers);if(mode==='action-413')return json(res,413,{code:'parser-operation-too-large'},headers);if(mode==='action-415')return json(res,415,{code:'parser-operation-media-type'},headers);if(mode==='action-429')return json(res,429,{code:'parser-operation-unavailable'},headers);if(mode==='action-500')return json(res,500,{code:'parser-operation-failed'},headers);const authority='2026-07-17T10:03:00Z';return json(res,200,{operationId:'44444444-4444-4444-8444-444444444444',action:url.pathname.split('/').at(-1),runId,affectedTaskCount:1,authorityAtUtc:authority,run:run(authority)},headers);}
    return empty(res,404,headers);
  }); }
export async function listenParserOperationsMock(server,port){await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(port,'127.0.0.1',resolve);});return `http://127.0.0.1:${port}`;}
